version: "3"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile_frontend
    tty: true
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd manga_walker_front && npm start"
    ports:
      - "3000:3000"

