# Generated by Django 3.2 on 2021-07-21 06:23

from django.db import migrations, models
import manga_walker_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_walker_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcomponent',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to=manga_walker_backend.models.upload_BookCoverImage_path),
        ),
    ]
