# Generated by Django 3.2 on 2021-07-21 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga_walker_backend', '0002_bookcomponent_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storebook',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='manga_walker_backend.bookcomponent'),
        ),
    ]
