# Generated by Django 3.2 on 2021-07-21 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga_walker_backend', '0003_alter_storebook_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcomponent',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to='cover'),
        ),
        migrations.AlterField(
            model_name='storebook',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manga_walker_backend.bookcomponent'),
        ),
    ]
