# Generated by Django 3.2 on 2021-07-23 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga_walker_backend', '0004_auto_20210721_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storebook',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manga_walker_backend.bookcomponent'),
        ),
    ]
